---
bkp_rclone_server_application:
  name: "rclone"
  type: "
    {%- if
        ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'RedHat' ) or
      ( ansible_distribution == 'AlmaLinux' ) or
        ( ansible_distribution == 'OracleLinux' ) or
        ( ansible_distribution == 'Fedora' )
    -%}
      {{ 'rpm' }}
    {%- elif
        ( ansible_distribution == 'Debian' ) or
        ( ansible_distribution == 'Ubuntu' )
    -%}
      {{ 'deb' }}
    {%- endif -%}
    "
  version: "latest"
  installed: true
...
