---
bkp_rclone_server_platforms:
  - "CentOS8"
  - "RedHat8"
  - "AlmaLinux8"
  - "Rocky8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Ubuntu22"
  - "Fedora33"
  - "Fedora35"
  - "Fedora36"
  - "Debian10"
  - "Debian11"

bkp_rclone_server_base:
  run:
    rclone: "/usr/bin/rclone"

bkp_rclone_server_profiles:
  deb:
    latest:
      origin: "https://downloads.rclone.org"
      packages:
        - file: "rclone-current-linux-amd64.deb"
          name: "rclone"
  rpm:
    latest:
      origin: "https://downloads.rclone.org"
      packages:
        - file: "rclone-current-linux-amd64.rpm"
          name: "rclone"
...
